global window Fs step Sig Hr  Tig order K Center;
Tig = importdata('allTestData.mat');
importdata('alldata.mat');
accData = importdata('accDataAll.mat');
window = 1000;
Fs = 125;
step = 250;
K = 2;
order = 10;
Center = accData.C{3};